version: "3.9"
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: .
      dockerfile: ./es_Dockerfile
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.0
    ports:
      - 15601:5601
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local